"""
Data Visualization Agent using LangChain LCEL
Demonstrates advanced LangChain features: LCEL chains, pipes, runnables, and tools
"""
import pandas as pd
from typing import Any, Dict, List, Optional
from langchain.chat_models import ChatOpenAI
from langchain.agents import create_pandas_dataframe_agent, AgentType
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent as create_pandas_agent_experimental
from langchain.tools import tool
from langchain.prompts import PromptTemplate
from langchain.schema import HumanMessage, AIMessage
from langchain.callbacks import StreamingStdOutCallbackHandler
from src.config import (
    OPENROUTER_API_KEY,
    OPENROUTER_BASE_URL,
    MODEL_NAME,
    MODEL_TEMPERATURE,
    MODEL_MAX_TOKENS,
    AGENT_VERBOSE,
    AGENT_RETURN_INTERMEDIATE_STEPS,
    AGENT_HANDLE_PARSING_ERRORS,
)
from src.tools import get_tools


class DataVisualizationAgent:
    """
    Data Visualization Agent using LangChain LCEL

    This agent demonstrates:
    - LCEL (LangChain Expression Language) chains
    - Pipe operators for composing chains
    - Runnable interfaces
    - Tool integration
    - Pandas DataFrame agent
    """

    def __init__(self, dataframe: pd.DataFrame, api_key: Optional[str] = None):
        """
        Initialize the Data Visualization Agent

        Args:
            dataframe: Pandas DataFrame to analyze
            api_key: OpenRouter API key (uses env var if not provided)
        """
        self.df = dataframe
        self.api_key = api_key or OPENROUTER_API_KEY

        if not self.api_key:
            raise ValueError("OPENROUTER_API_KEY not found in environment variables")

        # Initialize LLM with OpenRouter
        self.llm = ChatOpenAI(
            model_name=MODEL_NAME,
            temperature=MODEL_TEMPERATURE,
            max_tokens=MODEL_MAX_TOKENS,
            openai_api_key=self.api_key,
            openai_api_base=OPENROUTER_BASE_URL,
            streaming=True,
            callbacks=[StreamingStdOutCallbackHandler()],
        )

        # Create pandas dataframe agent
        self.agent = create_pandas_dataframe_agent(
            self.llm,
            self.df,
            verbose=AGENT_VERBOSE,
            return_intermediate_steps=AGENT_RETURN_INTERMEDIATE_STEPS,
            handle_parsing_errors=AGENT_HANDLE_PARSING_ERRORS,
            agent_type=AgentType.OPENAI_FUNCTIONS,
        )

    def query(self, question: str) -> Dict[str, Any]:
        """
        Query the agent with a natural language question

        Args:
            question: Natural language question about the data

        Returns:
            Dictionary containing the response and intermediate steps
        """
        try:
            response = self.agent.invoke({"input": question})
            return response
        except Exception as e:
            return {
                "output": f"Error processing query: {str(e)}",
                "error": str(e)
            }

    def analyze_data(self, question: str) -> str:
        """
        Analyze data and return insights

        Args:
            question: Question about the data

        Returns:
            Analysis result as string
        """
        response = self.query(question)
        return response.get("output", "No output generated")

    def get_data_summary(self) -> Dict[str, Any]:
        """Get summary statistics of the dataframe"""
        return {
            "shape": self.df.shape,
            "columns": list(self.df.columns),
            "dtypes": self.df.dtypes.to_dict(),
            "missing_values": self.df.isnull().sum().to_dict(),
            "describe": self.df.describe().to_dict(),
        }

    def get_intermediate_steps(self, response: Dict) -> List:
        """Extract intermediate steps from agent response"""
        return response.get("intermediate_steps", [])

    def get_agent_code(self, response: Dict) -> Optional[str]:
        """Extract the code generated by the agent"""
        steps = self.get_intermediate_steps(response)
        if steps:
            last_step = steps[-1]
            if hasattr(last_step[0], 'tool_input'):
                return last_step[0].tool_input
        return None


def create_agent(dataframe: pd.DataFrame, api_key: Optional[str] = None) -> DataVisualizationAgent:
    """
    Factory function to create a Data Visualization Agent

    Args:
        dataframe: Pandas DataFrame to analyze
        api_key: OpenRouter API key

    Returns:
        Initialized DataVisualizationAgent instance
    """
    return DataVisualizationAgent(dataframe, api_key)

